"""add saved_amount to financial_goals

Revision ID: 8cf5fbfb08dd
Revises: 
Create Date: 2026-07-16 01:06:20.040471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cf5fbfb08dd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "financial_goals",
        sa.Column(
            "saved_amount",
            sa.Numeric(),
            nullable=False,
            server_default="0",
        ),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('financial_goals', 'saved_amount')
    # ### end Alembic commands ###
